rem 一些环境的设置
call ..\lr_src.bat
SET ENVNAME=lrsvr_exp
SET RHOST=123.207.68.133
SET RPORT=22
SET RUSER=ubuntu
SET RPKEY=D:\zdhsoft\doc\key\rex_private.key
SET RDEST=/data/xn-lr-server-exp
SET PM2=exp.pm2.json
